import { FormEvent, useCallback, useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { Alert, Box, Button, Card, Chip, CircularProgress, Container, Divider, Rating, Stack, Tab, Tabs, TextField, Typography } from '@mui/material'
import PaymentRoundedIcon from '@mui/icons-material/PaymentRounded'
import PlayArrowRoundedIcon from '@mui/icons-material/PlayArrowRounded'
import UploadFileRoundedIcon from '@mui/icons-material/UploadFileRounded'
import CheckCircleRoundedIcon from '@mui/icons-material/CheckCircleRounded'
import ReplayRoundedIcon from '@mui/icons-material/ReplayRounded'
import SendRoundedIcon from '@mui/icons-material/SendRounded'
import AttachFileRoundedIcon from '@mui/icons-material/AttachFileRounded'
import { api, dateTime, money } from '../api'
import { useApp } from '../App'

type Timeline = { id: string; event_type: string; from_state?: string; to_state?: string; created_at: string; data: Record<string, unknown> }
type Delivery = { id: string; version: number; delivery_type: string; content: Record<string, unknown>; description: string; created_at: string }
type Revision = { id: string; revision_number: number; details: string; priority: string; created_at: string }
type Workspace = { id: string; order_number: string; state: string; amount: number; currency: string; requirements: Record<string,string>; due_at?: string; accepted_at?: string; created_at: string; buyer: { id: string; display_name: string }; seller: { id: string; display_name: string }; talent: { id: string; title: string }; timeline: Timeline[]; deliveries: Delivery[]; revisions: Revision[] }
type Message = { id: string; sender_id?: string; sender_name?: string; body: string; created_at: string }
const states: Record<string,string> = { CREATED:'주문 생성',PAYMENT_PENDING:'결제 대기',PAID:'결제 완료',REQUIREMENT_PENDING:'요구사항 대기',READY:'작업 준비',IN_PROGRESS:'작업 중',DELIVERED:'납품 완료',REVISION_REQUESTED:'수정 요청',ACCEPTED:'구매확정',COMPLETED:'거래 완료',CANCEL_REQUESTED:'취소 요청',CANCELLED:'취소',DISPUTED:'분쟁',REFUNDED:'환불' }

export function OrderWorkspacePage(){
  const {id}=useParams();const {me,notify}=useApp();const [order,setOrder]=useState<Workspace|null>(null);const [messages,setMessages]=useState<Message[]>([]);const [tab,setTab]=useState(0);const [message,setMessage]=useState('');const [delivery,setDelivery]=useState('');const [revision,setRevision]=useState('');const [rating,setRating]=useState(5);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [uploaded,setUploaded]=useState<{name:string;download_url:string;sha256:string}|null>(null)
  const load=useCallback(async()=>{try{const [workspace,chat]=await Promise.all([api<Workspace>(`/api/v1/orders/${id}`),api<{items:Message[]}>(`/api/v1/orders/${id}/messages`)]);setOrder(workspace);setMessages(chat.items)}catch(e){setError(e instanceof Error?e.message:'주문을 불러오지 못했습니다.')}},[id])
  useEffect(()=>{void load();const protocol=window.location.protocol==='https:'?'wss:':'ws:';const socket=new WebSocket(`${protocol}//${window.location.host}/api/v1/orders/${id}/messages/ws`);socket.onmessage=()=>{void load()};const poll=window.setInterval(()=>{void load()},15000);return()=>{socket.close();window.clearInterval(poll)}},[id,load])
  if(error)return <Container maxWidth="lg" sx={{py:7}}><Alert severity="error">{error}</Alert></Container>;if(!order)return <Box sx={{minHeight:420,display:'grid',placeItems:'center'}}><CircularProgress/></Box>
  const buyer=me?.id===order.buyer.id;const seller=me?.id===order.seller.id;const admin=Boolean(me?.permissions.includes('orders.manage'))
  const action=async(fn:()=>Promise<unknown>,success:string)=>{setBusy(true);try{await fn();notify(success,'success');await load()}catch(e){notify(e instanceof Error?e.message:'처리하지 못했습니다.','error')}finally{setBusy(false)}}
  const transition=(to:string)=>action(()=>api(`/api/v1/orders/${id}/transition`,{method:'POST',body:JSON.stringify({to,note:''})}),`주문 상태를 ${states[to]??to}(으)로 변경했습니다.`)
  const pay=()=>action(()=>api(`/api/v1/orders/${id}/pay`,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:'{}'}),'결제를 에스크로에 보관했습니다.')
  const deliver=()=>action(()=>api(`/api/v1/orders/${id}/deliveries`,{method:'POST',body:JSON.stringify({delivery_type:'text',content:{text:delivery},description:'텍스트 납품'})}),'납품했습니다.').then(()=>setDelivery(''))
  const requestRevision=()=>action(()=>api(`/api/v1/orders/${id}/revision`,{method:'POST',body:JSON.stringify({details:revision,priority:'normal',attachments:[]})}),'수정을 요청했습니다.').then(()=>setRevision(''))
  const send=async(event:FormEvent)=>{event.preventDefault();if(!message.trim())return;await action(()=>api(`/api/v1/orders/${id}/messages`,{method:'POST',body:JSON.stringify({body:message,attachments:[]})}),'메시지를 보냈습니다.');setMessage('')}
  const review=()=>action(()=>api(`/api/v1/orders/${id}/review`,{method:'POST',body:JSON.stringify({quality:rating,communication:rating,timeliness:rating,professionalism:rating,repurchase:true,body:'좋은 서비스였습니다.'})}),'리뷰를 등록했습니다.')
  const upload=async(file?:File)=>{if(!file)return;const data=new FormData();data.append('file',file);await action(async()=>{const result=await api<{name:string;download_url:string;sha256:string}>(`/api/v1/orders/${id}/files`,{method:'POST',body:data});setUploaded(result);setDelivery(current=>current?`${current}\n첨부: ${result.download_url}`:`첨부: ${result.download_url}`)},'파일을 안전하게 저장했습니다.')}
  return <Container maxWidth="xl" sx={{py:{xs:3,md:5}}}><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" gap={2} sx={{mb:3}}><Box><Stack direction="row" gap={1} alignItems="center"><Typography variant="h2">{order.talent.title}</Typography><Chip color="primary" label={states[order.state]??order.state}/></Stack><Typography color="text.secondary" sx={{mt:.5}}>{order.order_number} · 납기 {dateTime(order.due_at)}</Typography></Box><Box sx={{textAlign:{md:'right'}}}><Typography variant="caption" color="text.secondary">계약 금액</Typography><Typography variant="h3">{money(order.amount,order.currency)}</Typography></Box></Stack>
    <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',lg:'minmax(0,1fr) 340px'},gap:3,alignItems:'start'}}><Card sx={{overflow:'hidden'}}><Tabs value={tab} onChange={(_,value)=>setTab(value)} variant="scrollable"><Tab label="개요"/><Tab label="대화"/><Tab label={`납품 ${order.deliveries.length}`}/><Tab label={`수정 ${order.revisions.length}`}/><Tab label="이력"/></Tabs><Divider/>
      <Box sx={{p:{xs:2.5,sm:3.5}}}>{tab===0&&<><Typography variant="h3">계약 당사자</Typography><Typography sx={{mt:1}}>구매자 {order.buyer.display_name} · 판매자 {order.seller.display_name}</Typography><Typography variant="h3" sx={{mt:3}}>확정 요구사항</Typography><Box component="pre" sx={{whiteSpace:'pre-wrap',fontFamily:'inherit',bgcolor:'#f6f8fc',p:2,borderRadius:2}}>{JSON.stringify(order.requirements,null,2)}</Box></>}
      {tab===1&&<><Stack spacing={1.5} sx={{maxHeight:430,overflowY:'auto',mb:2}}>{messages.map(item=><Box key={item.id} sx={{alignSelf:item.sender_id===me?.id?'flex-end':'flex-start',maxWidth:'78%',bgcolor:item.sender_id===me?.id?'primary.light':'#f0f3f7',p:1.5,borderRadius:2}}><Typography variant="caption" color="text.secondary">{item.sender_name} · {dateTime(item.created_at)}</Typography><Typography>{item.body}</Typography></Box>)}</Stack><Box component="form" onSubmit={send}><Stack direction="row" gap={1}><TextField fullWidth value={message} onChange={e=>setMessage(e.target.value)} label="메시지"/><Button type="submit" variant="contained" aria-label="메시지 보내기"><SendRoundedIcon/></Button></Stack></Box></>}
      {tab===2&&<Stack spacing={2}>{order.deliveries.map(item=><Card key={item.id} variant="outlined" sx={{p:2,boxShadow:'none'}}><Typography fontWeight={750}>납품 v{item.version} · {dateTime(item.created_at)}</Typography><Typography sx={{mt:1}}>{item.description}</Typography><Box component="pre" sx={{whiteSpace:'pre-wrap'}}>{JSON.stringify(item.content,null,2)}</Box></Card>)}</Stack>}
      {tab===3&&<Stack spacing={2}>{order.revisions.map(item=><Alert key={item.id} severity="warning"><Typography fontWeight={750}>수정 #{item.revision_number}</Typography>{item.details}</Alert>)}</Stack>}
      {tab===4&&<Stack spacing={1.5}>{order.timeline.map(item=><Box key={item.id}><Typography fontWeight={700}>{states[item.to_state??'']??item.event_type}</Typography><Typography variant="body2" color="text.secondary">{dateTime(item.created_at)}</Typography></Box>)}</Stack>}</Box></Card>
      <Card sx={{p:3,position:{lg:'sticky'},top:96}}><Typography variant="h3">다음 작업</Typography><Typography color="text.secondary" sx={{mt:.7,mb:2.5}}>현재 상태에 맞는 작업만 표시됩니다.</Typography><Stack spacing={1.5}>
        {(buyer||admin)&&(order.state==='CREATED'||order.state==='PAYMENT_PENDING')&&<Button variant="contained" startIcon={<PaymentRoundedIcon/>} onClick={pay} disabled={busy}>결제하고 작업 준비</Button>}
        {(seller||admin)&&(order.state==='READY'||order.state==='REVISION_REQUESTED')&&<Button variant="contained" startIcon={<PlayArrowRoundedIcon/>} onClick={()=>transition('IN_PROGRESS')} disabled={busy}>작업 시작</Button>}
        {(seller||admin)&&order.state==='IN_PROGRESS'&&<><TextField multiline minRows={4} label="납품 내용" value={delivery} onChange={e=>setDelivery(e.target.value)}/><Button component="label" variant="outlined" startIcon={<AttachFileRoundedIcon/>}>결과 파일 첨부<input hidden type="file" onChange={e=>upload(e.target.files?.[0])}/></Button>{uploaded&&<Alert severity="success">{uploaded.name}<br/><Typography variant="caption">SHA-256 {uploaded.sha256}</Typography></Alert>}<Button variant="contained" startIcon={<UploadFileRoundedIcon/>} onClick={deliver} disabled={busy||!delivery.trim()}>납품하기</Button></>}
        {(buyer||admin)&&order.state==='DELIVERED'&&<><Button variant="contained" color="success" startIcon={<CheckCircleRoundedIcon/>} onClick={()=>action(()=>api(`/api/v1/orders/${id}/accept`,{method:'POST',body:'{}'}),'구매확정했습니다.')} disabled={busy}>구매확정</Button><TextField multiline minRows={3} label="수정할 내용" value={revision} onChange={e=>setRevision(e.target.value)}/><Button variant="outlined" color="warning" startIcon={<ReplayRoundedIcon/>} onClick={requestRevision} disabled={busy||!revision.trim()}>수정 요청</Button></>}
        {buyer&&order.state==='ACCEPTED'&&<><Typography fontWeight={700}>서비스 평가</Typography><Rating value={rating} onChange={(_,value)=>setRating(value??5)} size="large"/><Button variant="contained" onClick={review} disabled={busy}>리뷰 등록하고 완료</Button></>}
        {order.state==='COMPLETED'&&<Alert severity="success">거래가 완료되었습니다.</Alert>}
      </Stack></Card></Box></Container>
}
