import { useEffect, useState } from 'react'
import { useNavigate, useParams, Link as RouterLink } from 'react-router-dom'
import { Alert, Box, Button, Card, Chip, CircularProgress, Container, Divider, MenuItem, Stack, TextField, Typography } from '@mui/material'
import ShoppingBagOutlinedIcon from '@mui/icons-material/ShoppingBagOutlined'
import ScheduleRoundedIcon from '@mui/icons-material/ScheduleRounded'
import ReplayRoundedIcon from '@mui/icons-material/ReplayRounded'
import VerifiedRoundedIcon from '@mui/icons-material/VerifiedRounded'
import { api, money } from '../api'
import { useApp } from '../App'

type Package = { id: string; package_type: string; name: string; description: string; price: number; delivery_days: number; revision_count: number; features: unknown[] }
type Requirement = { id: string; label: string; help_text: string; field_type: string; required: boolean; options: unknown[] }
type Detail = { id: string; title: string; summary: string; description: string; service_type: string; base_price: number; currency: string; delivery_days: number; revision_count: number; tags: string[]; deliverables: unknown[]; seller: { id: string; display_name: string }; packages: Package[]; requirements: Requirement[] }

export function TalentPage() {
  const { id } = useParams(); const { me, notify } = useApp(); const navigate = useNavigate(); const [talent, setTalent] = useState<Detail | null>(null); const [selectedPackage, setSelectedPackage] = useState(''); const [requirements, setRequirements] = useState<Record<string, string>>({}); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState('')
  useEffect(() => { api<Detail>(`/api/v1/talents/${id}`).then((data) => { setTalent(data); setSelectedPackage(data.packages[0]?.id ?? '') }).catch((e) => setError(e.message)) }, [id])
  if (error) return <Container maxWidth="lg" sx={{ py: 7 }}><Alert severity="error">{error}</Alert></Container>
  if (!talent) return <Box sx={{ minHeight: 420, display: 'grid', placeItems: 'center' }}><CircularProgress /></Box>
  const pkg = talent.packages.find((item) => item.id === selectedPackage)
  const order = async () => { if (!me) { navigate('/login', { state: { from: `/talents/${id}` } }); return }; setSubmitting(true); try { const result = await api<{ id: string }>('/api/v1/orders', { method: 'POST', body: JSON.stringify({ talent_id: talent.id, package_id: selectedPackage || undefined, requirements, options: [] }) }); notify('주문을 만들었습니다.', 'success'); navigate(`/orders/${result.id}`) } catch (cause) { notify(cause instanceof Error ? cause.message : '주문하지 못했습니다.', 'error') } finally { setSubmitting(false) } }
  return <Container maxWidth="lg" sx={{ py: { xs: 4, md: 7 } }}><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'minmax(0,1fr) 360px' }, gap: 4, alignItems: 'start' }}>
    <Box><Stack direction="row" gap={1} sx={{ mb: 2 }}><Chip label={talent.service_type} color="primary" /><Stack direction="row" alignItems="center" gap={.5}><VerifiedRoundedIcon color="secondary" fontSize="small" /><Typography fontWeight={700}>{talent.seller.display_name}</Typography></Stack></Stack><Typography variant="h1" sx={{ fontSize: 'clamp(2rem,4vw,3.5rem)' }}>{talent.title}</Typography><Typography sx={{ mt: 2, fontSize: '1.1rem' }} color="text.secondary">{talent.summary}</Typography><Stack direction="row" gap={1} flexWrap="wrap" sx={{ mt: 3 }}>{talent.tags.map((tag) => <Chip key={tag} label={tag} variant="outlined" />)}</Stack><Divider sx={{ my: 4 }} /><Typography variant="h3">서비스 소개</Typography><Typography sx={{ mt: 2, whiteSpace: 'pre-wrap' }}>{talent.description}</Typography><Typography variant="h3" sx={{ mt: 4 }}>주문 전 정보</Typography>{talent.requirements.length === 0 ? <Typography color="text.secondary" sx={{ mt: 1 }}>추가로 입력할 필수 정보가 없습니다.</Typography> : <Stack spacing={2} sx={{ mt: 2 }}>{talent.requirements.map((item) => <TextField key={item.id} required={item.required} label={item.label} helperText={item.help_text} value={requirements[item.id] ?? ''} onChange={(e) => setRequirements({ ...requirements, [item.id]: e.target.value })} multiline={item.field_type === 'textarea'} minRows={item.field_type === 'textarea' ? 3 : undefined} />)}</Stack>}</Box>
    <Card sx={{ p: 3, position: { md: 'sticky' }, top: 96 }}><Typography variant="h3">주문 구성</Typography>{talent.packages.length > 0 && <TextField select fullWidth label="패키지" value={selectedPackage} onChange={(e) => setSelectedPackage(e.target.value)} sx={{ mt: 2 }}>{talent.packages.map((item) => <MenuItem key={item.id} value={item.id}>{item.name} · {money(item.price, talent.currency)}</MenuItem>)}</TextField>}<Stack spacing={1.3} sx={{ my: 3 }}><Stack direction="row" gap={1}><ScheduleRoundedIcon color="action" /><Typography>{pkg?.delivery_days ?? talent.delivery_days}일 납기</Typography></Stack><Stack direction="row" gap={1}><ReplayRoundedIcon color="action" /><Typography>무료 수정 {pkg?.revision_count ?? talent.revision_count}회</Typography></Stack></Stack><Divider /><Box sx={{ my: 3 }}><Typography variant="caption" color="text.secondary">총 주문 금액</Typography><Typography variant="h2">{money(pkg?.price ?? talent.base_price, talent.currency)}</Typography></Box><Button fullWidth variant="contained" size="large" startIcon={<ShoppingBagOutlinedIcon />} onClick={order} disabled={submitting}>{me ? submitting ? '주문 생성 중…' : '주문하기' : '로그인하고 주문하기'}</Button>{me?.id === talent.seller.id && <Button fullWidth component={RouterLink} to="/profile/seller" sx={{ mt: 1 }}>내 상품 관리</Button>}</Card>
  </Box></Container>
}
